### ISSUE TITLE
"replace deno?" EOF or read error

### ISSUE THREAD

**Issue by crabmusket** [denoland/deno_install#100]
I just tried updating from 0.35 to 0.38 using the script. This is what happens in the terminal:

```
$ which deno
/home/daniel/.local/bin/deno

$ deno --version
deno 0.35.0
v8 8.1.310
typescript 3.8.2

$ curl -fsSL https://deno.land/x/install/install.sh | sh
######################################################################## 100.0%
Archive:  /home/daniel/.local/bin/deno.zip
replace deno? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)

$ uname -a
Linux hostname 4.4.0-176-generic #206-Ubuntu SMP Fri Feb 28 05:02:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

That `EOF or read error` happens immediately; it doesn't seem like there's a chance for me to do anything.

**Solved** by removing the existing deno binary first.

**Comment by lucacasonato** [comment]
Got that too

**Comment by ry** [comment]
Thanks for the notice. This must be from changes made in b635b52.


I think that using "-o" with unzip will fix this https://github.com/denoland/deno_install/pull/101

**Comment by MarkTiedemann** [comment]
cc @bartlomieju I think #101 fixed this so this issue can be closed.
