### ISSUE TITLE
When trying to install in wsl2 using ubuntu as Distro, the script for shell doesn't work

### ISSUE THREAD

**Issue by JMercie** [denoland/deno_install#109]
When trying to run the next script in bash or zsh "curl -fsSL https://deno.land/x/install/install.sh | sh "

print this message: "sh 39: unzip: not found"

Is this a known issue. Does it have a workaround? 

thanks

**Comment by MarkTiedemann** [comment]
This means that the `unzip` utility is required. The work-around is installing `unzip`, for example, with `sudo apt-get install unzip`.

**Comment by JMercie** [comment]
@MarkTiedemann  Thank you so much, it works! I'm going to close the issue.
