### ISSUE TITLE
Update deno in brew

### ISSUE THREAD

**Issue by SantiMA10** [denoland/deno_install#110]
When you install deno with brew it doesn't install the latest version

**Comment by MarkTiedemann** [comment]
https://formulae.brew.sh/formula/deno should install v0.42.0, the latest stable version.

**Comment by lucacasonato** [comment]
@MarkTiedemann v0.42.0 is not the latest anymore. v1.0.0-rc1 was released yesterday: https://github.com/denoland/deno/releases/tag/v1.0.0-rc1.

@SantiMA10 The brew formula needs to be manually updated after every release. That can sometimes take a few days.

**Comment by nimabrownlee** [comment]
Any update on this?

**Comment by md-seb** [comment]
Today ```brew install deno``` has installed deno@1.0.0 for me on OSX

```
~/deno % brew info deno
deno: stable 1.0.0 (bottled)
Command-line JavaScript / TypeScript engine
https://deno.land/
/usr/local/Cellar/deno/1.0.0 (9 files, 42.0MB) *
  Poured from bottle on 2020-05-14 at 09:40:51
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/deno.rb
==> Dependencies
Build: llvm ✘, ninja ✘, rust ✘
==> Requirements
Build: xcode ✘
Required: macOS is required ✔
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
```
