### ISSUE TITLE
1.0.0 version broken with asdf - deno.gz: not in gzip format

### ISSUE THREAD

**Issue by jeanlescure** [denoland/deno_install#112]
Getting the following output when trying to install v1.0.0 with asdf:

```
$ asdf install deno 1.0.0
∗ Downloading and installing deno...

gzip: /home/jeanlescure/.asdf/installs/deno/1.0.0/bin/deno.gz: not in gzip format
Fail: Could not uncompress
Fail: An error occurred
```

**Comment by MarkTiedemann** [comment]
@jeanlescure I think this issue should be moved to this repo: https://github.com/asdf-community/asdf-deno

**Comment by jeanlescure** [comment]
Went ahead and created [the issue](https://github.com/asdf-community/asdf-deno/issues/11) in the proper repo. Thanks @MarkTiedemann :+1:

**Comment by MarkTiedemann** [comment]
Thanks, @jeanlescure!
Since the root cause is fixed now, do you want to close this issue?

**Comment by jeanlescure** [comment]
Sure thing
