### ISSUE TITLE
Clean version API

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno_install#115]
The _"Keep this script simple and easily auditable"_ `install.ps1` script has, at its core, a 20 line mess to determine the latest Deno version for Windows:

https://github.com/denoland/deno_install/blob/bd28456269a17a0809e7ca518e199bb9daad557b/install.ps1#L32-L52

(And I know it's a mess because I wrote the damn mess. :))

Deno being on v1.0.0 now, I think it's time to clean up a bit...

I know @lucacasonato tried to create a version API using a worker in https://github.com/denoland/deno_website2/pull/180.

I'd propose an even simpler API: All it's supposed to do is return the latest version released and available on GitHub Releases for each platform as a string, e.g. `GET /api/version/windows` returns `v1.0.0`.

Internally, the API would make the same mess that the installer script does at the moment, e.g. parse the HTML from `https://github.com/denoland/deno/releases`, check for the first anchor tag that matches a Windows release, return the number (plus some caching maybe).

If we had an API like that, those 20 lines would be a single one...

Not to mention that the same mess happens in the `install.sh` script which would benefit massively from this API as well.

**Comment by MarkTiedemann** [comment]
I built an API like that for a personal project: https://gist.github.com/MarkTiedemann/6ec5dc6b4f968296fa7e7b578ca91ad6

Again, we could greatly simplify both of our installer scripts with an official API like this. :)

**Comment by bartlomieju** [comment]
@ry PTAL

**Comment by Summpot** [comment]
I've made a pr #152  which looks like [this](https://github.com/denoland/deno_install/pull/152/files#diff-00ded903b18eba5a23a1d8ec86c58e94L28-R55).
@MarkTiedemann

**Comment by MarkTiedemann** [comment]
Hi @Summpot. The reason why we can't use the GitHub API to get the latest release is that it is rate-limited, unless you provide a GitHub token. However, we cannot expect everyone to get a GitHub token before installing Deno using the script. That's why we parse the non-rate-limited releases page (`https://github.com/denoland/deno/releases`), which is plain HTML, to get the latest version reliably.

**Comment by maximousblk** [comment]
GitHub provides a mirror to the latest release and it's assets at:
- release: `https://github.com/:owner:/repo/releases/latest`
- assets: `https://github.com/:owner:/repo/releases/latest/download/:asset`

This doesn't depend on github api, so isn't rate limited, and also cleans up the mess to absolute minimal.

see #167
