### ISSUE TITLE
Shorter installer URL

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno_install#123]
https://deno.land/x/install/install.sh -> https://deno.land/install.sh,  https://deno.land/x/install/install.ps1 -> https://deno.land/install.ps1 would be nice.

**Comment by brkeejp** [comment]
I think url easy enought

**Comment by MarkTiedemann** [comment]
This has been fixed in the meanwhile:

- https://deno.land/install.ps1 already redirects to https://deno.land/x/install@v$version/install.ps1, and
- https://deno.land/install.sh already redirects to https://deno.land/x/install@v$version/install.sh.

The documentation in this repo still needs to be updated.
