### ISSUE TITLE
Install.sh fails in windows with error - Unexpected token 'https://deno.land/x/install/install.ps1' in expression or statement.

### ISSUE THREAD

**Issue by charan2009** [denoland/deno_install#125]
PS C:\Users\charanp> $iwr https://deno.land/x/install/install.ps1 -useb | iex
Unexpected token 'https://deno.land/x/install/install.ps1' in expression or statement.
At line:1 char:45
+ $iwr https://deno.land/x/install/install.ps1 <<<<  -useb | iex
    + CategoryInfo          : ParserError: (https://deno.land/x/install/install.ps1:String) [], ParentContainsErrorRec
   ordException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by MarkTiedemann** [comment]
You are using `$iwr` rather than `iwr`. Just remove the $-sign. :)

**Comment by charan2009** [comment]
if i remove the $ symbol....i get following error
PS C:\Users\charanp> iwr https://deno.land/x/install/install.ps1 -useb | iex
The term 'iwr' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spellin
g of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:4
+ iwr <<<<  https://deno.land/x/install/install.ps1 -useb | iex
    + CategoryInfo          : ObjectNotFound: (iwr:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Do i need to install anything else before installing deno...
iam using windows 7

**Comment by lucacasonato** [comment]
I don't know if the `iwr` alias is available on Windows 7.

Can you try `Invoke-WebRequest https://deno.land/x/install/install.ps1 -useb | iex`?

**Comment by MarkTiedemann** [comment]
Windows 7 was released in 2009. Windows 8 was released in 2012.

Invoke-WebRequest was introduced in PowerShell 3.0, which was released in 2012 with Windows 8.

@charan2009 I'm sorry but the PowerShell installer won't work on Windows 7.

---

Then again, you don't need the installer. You can install Deno manually. :)

Deno ships as a single executable file that you can download from the releases page (https://github.com/denoland/deno/releases). For more details, please check this comment: https://github.com/denoland/deno/issues/5727#issuecomment-633668916

---

On yet another note, I don't know whether anyone has tested Deno on Windows 7 yet. It may or may not work...

---

ref https://github.com/denoland/deno_install/issues/130

---

cc @bartlomieju, I think this issue can be closed now.
