### ISSUE TITLE
Improve install script for WSL

### ISSUE THREAD

**Issue by brandonkal** [denoland/deno_install#127]
The install script makes the assumption that unzip is available. It is not available by default in WSL and probably other environments. Ideally the script would check for this before downloading deno.

It would then prompt the user to install unzip with apt and exit.

**Comment by MarkTiedemann** [comment]
Would be fixed by https://github.com/denoland/deno_install/pull/122.

**Comment by MarkTiedemann** [comment]
cc @bartlomieju Fixed by #122. This can be closed.
