### ISSUE TITLE
Can't install deno with powershell behind corporate proxy

### ISSUE THREAD

**Issue by niyarlatotep** [denoland/deno_install#129]
If i set proxy explitly in  iwr -Proxy, it stucks on:
```
+ Invoke-WebRequest $DenoUri -OutFile $DenoZip -UseBasicParsing
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [InvokeWebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```
Is there a way to improve this?

**Comment by MarkTiedemann** [comment]
As a work-around, you can download https://deno.land/x/install/install.ps1, edit the file and set `-Proxy` (`-ProxyCredential` / `-ProxyUseDefaultCredentials`) for all other `Invoke-WebRequest` invocations, then run `.\install.ps1`.

Note that you can also manually download Deno. No "installation" is necessary. A release will ship a zip-file: https://github.com/denoland/deno/releases/download/v1.0.2/deno-x86_64-pc-windows-msvc.zip If you download and extract the zip-file, you will find `deno.exe` in there. (The `install.ps1`-script does the same: It determines the latest Deno version, then downloads and extracts the zip-file. It also adds Deno to your path - but you could do that manually, too.)
