### ISSUE TITLE
Add arch / manjaro install instructions

### ISSUE THREAD

**Issue by Yamboy1** [denoland/deno_install#131]
It's probably a good idea to add instructions for installing from the aur:
```
sudo pacman -S deno-bin
```
(DISCLAIMER: I am the maintainer of this package)

**Comment by MarkTiedemann** [comment]
There's a related PR: https://github.com/denoland/deno_install/pull/128

**Comment by MarkTiedemann** [comment]
With both #128 and #137 merged, I think this issue can be closed.

Thanks again, @Yamboy1 and @naueramant!

cc @bartlomieju
