### ISSUE TITLE
Make sure deno can be added as a node version in nvm

### ISSUE THREAD

**Issue by ruurd** [denoland/deno_install#132]
Make sure deno can be added as a node version in [nvm](https://github.com/nvm-sh/nvm). This simplifies juggling multiple versions of deno for developers that want to explore newer versions while having to use older versions in certain projects.

**Comment by MarkTiedemann** [comment]
Node and Deno are different projects. I don't think you ever will be able to install Deno using nvm. And if you'd like Deno to be integrated in nvm, I suggest you open an issue at the nvm repo.

If you want an nvm replacement for Deno, there's dvm: https://github.com/axetroy/dvm

**Comment by ruurd** [comment]
Reason enough NOT to use deno then. Oh and BTW stop selling it as a safe node fork.

**Comment by MarkTiedemann** [comment]
It is neither a fork of Node, nor is it sold as one. Don't know where you got that info. Please check the official website, https://deno.land, to see how Deno is actually "sold".

Deno is sold as a secure runtime. In comparison to Node, it certainly has a different, more secure architecture. But again, that does not mean it's sold as Node fork. On the contrary, it is a completely different project so it would not make any sense to sell it as a fork of Node.

Again, Deno not being integrated into the Node Version Manager - which, by the way, is a completely separate community project, not an official Node project - should be a deal breaker here. There's plenty of ways to install Deno and manage multiple versions of it. If those don't fit you, please let us know how we can improve the installation process / version management for you.

Then again, if you want Deno to be integrated into nvm, I suggest you open an issue at the nvm repo: https://github.com/nvm-sh/nvm
