### ISSUE TITLE
Redundant `uname -m` test in installer script

### ISSUE THREAD

**Issue by elibarzilay** [denoland/deno_install#139]
https://github.com/denoland/deno_install/blob/6272499aa1037e388dc4e2d9dccd0b9faa3beecc/install.sh#L22

This test is already done at the top.

(Picky, but given the refreshingly short script and the comment on top, it seems worthy of fixing.)

**Comment by MarkTiedemann** [comment]
@elibarzilay You are right, thanks for pointing this out! That looks like a merge mistake to me (we had a bunch of PRs being merged in the past few days).
