### ISSUE TITLE
Update PowerShell specific-version installation instructions for GitHub Releases

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno_install#144]
While working on updating the PowerShell specific-version installation (https://github.com/denoland/deno_install/pull/143), I noticed that the releases page (https://github.com/denoland/deno/releases) uses the old temp file installation, e.g. `iwr $url -useb -outf install.ps1; .\install.ps1 $version` rather than the new one using the `$v` variable: `$v="$version"; iwr $url -useb | iex`. The temp file installation doesn't work anymore with the new installer. So I think we either have to update the releases with the new instructions or change the installer so the temp file installation works again. I think both are viable options so I'm looking for feedback on this topic.

cc @bartlomieju 

EDIT: In any case, it would make sense to merge (or close) #143 before updating the instructions.

**Comment by ry** [comment]
I've updated [the instructions on the 1.0.3 release](https://github.com/denoland/deno/releases/tag/v1.0.3). The old docs are broken because of the API change.

We should freeze changes to deno_install's commands so we don't break old documentation.

**Comment by MarkTiedemann** [comment]
@ry It's possible that both $v and the first argument work in which case the old docs would still work. I'll send a PR for it later.
