### ISSUE TITLE
Powershell installer doesn't work on Windows 8.1 updater as well

### ISSUE THREAD

**Issue by Niyarlatotep** [denoland/deno_install#146]
Powershell 4 on Windows 8.1 doesn't support Expand-Archive command on trying to install or update deno it shows error:
```
iex : The term 'Expand-Archive' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:53
+ iwr https://deno.land/x/install/install.ps1 -useb | iex
+                                                     ~~~
    + CategoryInfo          : ObjectNotFound: (Expand-Archive:String) [Invoke-Expression], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```
It might be replaced by System.IO.Compression.ZipFile

**Comment by MarkTiedemann** [comment]
`Expand-Archive` should be available since PowerShell 5.1: https://docs.microsoft.com/de-de/powershell/module/microsoft.powershell.archive/Expand-Archive?view=powershell-5.1

Can you print the output of `$PSVersionTable`?

In any case, I think there's two ways to fix this: 1) You could upgrade your system. 2) We could add a workaround for older systems, such as,

```powershell
# Requires .NET Framework 4.5+
Add-Type -AssemblyName System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::ExtractToDirectory($zip, $out)
```
```powershell
# Requires Win32 COM APIs which are not available in PowerShell Core
$shell = New-Object -ComObject Shell.Application
$shell.Namespace($out).CopyHere($shell.Namespace($zip).items())
```

**Comment by Niyarlatotep** [comment]
```
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.19170
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```
I tryied to fix it like in first variant but faced that ExtractToDirectory method can't overrite files if i try to pass $true as third argument it throws error. It could be solved by delting deno.exe if exists but it ther are other files in the future it could be a proble. Does the second variant support overriting?

**Comment by Niyarlatotep** [comment]
In any case I'll update my powershell version thank you!

**Comment by MarkTiedemann** [comment]
While PowerShell 4 is the default installation on Windows 8.1, PowerShell 5 is available for Windows 7-10: If you want to upgrade, please checkout the upgrade documentation: https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/install/installing-windows-powershell#upgrading-existing-windows-powershell

> I tryied to fix it like in first variant but faced that ExtractToDirectory method can't overrite files if i try to pass $true as third argument it throws error.

For .NET 4.5, there's no `overwriteFiles` option (see https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile.extracttodirectory?view=netframework-4.5). It is only available in newer .NET and .NET Core versions.

>  It could be solved by delting deno.exe if exists but if ther are other files in the future it could be a problem.

Indeed - that would fix it. Luckily, Deno will only ever ship as a single `.exe` so "other files in future" are not a concern. :)

> Does the second variant support overriting?

No, it does not (see https://docs.microsoft.com/en-us/windows/win32/shell/folder-copyhere).

---

I think supporting Windows 8.1 is fine, so I'll make a PR to update the installer.

Again, thanks for reporting this issue, @Niyarlatotep!

**Comment by Niyarlatotep** [comment]
@MarkTiedemann Thank you! One more question. I noticed that deno upgrate uses the same powershell command Expand-Archive. Should we do anything with it? 
```
Command::new("powershell.exe")
          .arg("-Command")
          .arg("Expand-Archive")
          .arg("-Path")
          .arg(&archive_path)
          .arg("-DestinationPath")
          .arg(&temp_dir)
          .spawn()?
          .wait()?

```

**Comment by MarkTiedemann** [comment]
Yes, you are right - I think that code should be updated as well. @Niyarlatotep Do you want to send a PR?

**Comment by Niyarlatotep** [comment]
@MarkTiedemann unfortunately I'm just slightly familiar with Rust.

**Comment by MarkTiedemann** [comment]
> @MarkTiedemann unfortunately I'm just slightly familiar with Rust.

@Niyarlatotep  Same, I have barely written any Rust so far.

If you want to give it a try, I'm sure there's plenty of people that would help you out (you can also for help on Discord: https://discord.gg/deno).
