### ISSUE TITLE
Uninstall Deno documentation

### ISSUE THREAD

**Issue by ipelekhan** [denoland/deno_install#155]
Hi,

I have installed Deno using Powershell on Windows 10. Want to switch to choco package manager, but not sure if things will not get messed up. So the question is how to uninstall Deno correctly? Are there any scripts for that or manual with steps?

Thanks in advance!

**Comment by MarkTiedemann** [comment]
Hi @ipelekhan, by default, the installer will put `deno.exe` into `%userprofile%\.deno\bin`, e.g. `C:\Users\ipelekhan\.deno\bin\deno.exe`. Currently, there is no uninstall documentation (nor an uninstall script). But if you want to uninstall Deno, you can just delete that folder.

Note that Deno will also add `%userprofile%\.deno\bin` to your `%path%` variable. If you want to undo that, you'll have to adjust it as well.

Hope this helps.

**Comment by ipelekhan** [comment]
Thanks for clarification! Reinstalled Deno with no issues. Thanks!
