### ISSUE TITLE
Windows SSL Tls11

### ISSUE THREAD

**Issue by Indribell** [denoland/deno_install#16]
The following issue shows up when trying to install on Windows 10.

```
iwr : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:6
+ iex (iwr https://deno.land/x/install/install.ps1)
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```
You need to do first do the following command in your powershell.

```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

This command is present on line 7 of the install.ps1 script, but the script errors out before it reaches this line. Because this needs to be set to establish a connection and when you try to connect to "set the command", you already run into the Tls11 issue.

Maybe its better to update the documentation? Or have a batch file that the user download, where this command is set first, before the iex command is run.

**Comment by hayd** [comment]
I believe there is a config in cloudfront (to allow more lax/legacy protocol)...

**Comment by hayd** [comment]
Is it github? https://github.com/denoland/deno_install/issues/15#issuecomment-451314167

**Comment by MarkTiedemann** [comment]
I know I had weird issues with setting the Security Protocol before, mostly PowerShell or .NET internal errors. Just today, for example, I randomly hit a bunch of `Powershell pipeline returned an error` errors when trying to set the Security Protocol on a different machine. Usually, in those cases, restarting Windows magically solved the problem... I know that's not a satisfying answer, quite cliché, and I hate to ask, but have you tried rebooting your system? :)

**Comment by MarkTiedemann** [comment]
Since #45 is merged, this issue can be closed.

cc @ry

**Comment by ry** [comment]
thx
