### ISSUE TITLE
[ask] Which image to use for dockerization?

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [denoland/deno_install#162]
Greetings, is there an official way to install deno with a docker image? or with a .yaml to use docker-compose.

**Comment by lucacasonato** [comment]
No there is no official image right now. https://github.com/hayd/deno-docker are good though

Closing as duplicate of https://github.com/denoland/deno/issues/3356

**Comment by EdwinBetanc0urt** [comment]
Thanks for responding @lucacasonato , I will check that docker image.
