### ISSUE TITLE
Linux 20.04 - deno install not specifying path in bash

### ISSUE THREAD

**Issue by HenrySabio** [denoland/deno_install#165]
After some trial and error I realized that I needed to manually add the following to my `.bashrc` file:

```sh
export DENO_INSTALL="/home/$USER/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
```
Otherwise `deno` command would return an error as if not installed unless I used the direct path instead.
This should either be added to the `readme` file under installation section for MacOS/Linux or done for the user during install.

My system/environment:
Dell XPS - Developer Edition (Linux OEM)
Ubuntu 20.04 - Fresh Install, all default settings & apps out of box

(Contribution Newbie - forgive me if I missed references to this in existing Issues/PRs, improper formatting, or if this is intentional by design.)

**Comment by treedbox** [comment]
**Install Deno on linux Debian 10**
`curl -fsSL https://deno.land/x/install/install.sh | sh`
Deno was installed successfully to /root/.deno/bin/deno
$HOME/.bash_profile (or similar):
`nano $HOME/.bashrc`
Manually add:
```
export DENO_INSTALL="/home/$USER/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
```
save.

Open a new tab/window
`deno --version`
The output should be something like:
```
deno 1.5.4 (bc79d55, release, x86_64-unknown-linux-gnu)
v8 8.8.278.2
typescript 4.0.5
```
