### ISSUE TITLE
Support installing canary versions

### ISSUE THREAD

**Issue by Liamolucko** [denoland/deno_install#169]
It'd be nice if this could be used to install canary versions of Deno; maybe using a `--canary` flag or specifying it in the version.

**Comment by crowlKats** [comment]
deno_install scripts should stay simple to be easily auditable. anyone who'd even want to use a canary version would already be using deno anyways, so they can just use the upgrade command.

**Comment by Liamolucko** [comment]
Fair enough; I'll close this then.
