### ISSUE TITLE
[FRE] Would there be official container images of deno on ducker hub ?

### ISSUE THREAD

**Issue by yw662** [denoland/deno_install#174]
It would be great if one can use deno with docker by a simple `image: deno`, or `image: deno:debian` etc. It would be a great help for CI/CD, and so many other use cases.

Node.js have [these images](https://hub.docker.com/_/node) indeed.

**Comment by crowlKats** [comment]
Duplicate of denoland/deno#3356

**Comment by lucacasonato** [comment]
https://hub.docker.com/r/denoland/deno
