### ISSUE TITLE
deno formular for homebrew is not updated

### ISSUE THREAD

**Issue by hoangph271** [denoland/deno_install#179]
As for today, the Deno formula for homebrew is still stuck at 1.7.2...!
The new stable release of Deno is now 1.7.5...?
--
Can anyone please create a PR for homebrew...?

**Comment by crowlKats** [comment]
https://github.com/Homebrew/homebrew-core/pull/71518

**Comment by hoangph271** [comment]
> There already is a PR. [Homebrew/homebrew-core#71518](https://github.com/Homebrew/homebrew-core/pull/71518)

Thank you, what I shame of me not doing my research properly...!

I wonder what take them so long...!
