### ISSUE TITLE
[Feature Request] Deno can installed with brew in Linux

### ISSUE THREAD

**Issue by darkRaspberry** [denoland/deno_install#180]
We can all agree with the fact that https://brew.sh is a good package manger not only for mac os but also with Linux. Because many use it with Linux as Linux-brew.

Like if I install now deno with brew then.

```
dev@ubu27x:~$ brew install deno
deno: macOS is required for this software.
Error: An unsatisfied requirement failed this build.

```

Node, npm are easily installed by brew in Linux. And also many many other package are also shipped with brew. Brew remove all the permission errors and many dev like it. Hope you understand.

Also brew keep all the package update with a single command.

**Comment by lucacasonato** [comment]
We don't maintain the brew distribution for Deno. Please open a feature request upstream with Brew. Thanks!

**Comment by darkRaspberry** [comment]
@lucacasonato That's nice. Thanks for responding.
