### ISSUE TITLE
Error installing Deno using `iwr` (again?)

### ISSUE THREAD

**Issue by saschanaz** [denoland/deno_install#202]
#191 said it's fixed but it's not.

```
> pwsh --version
PowerShell 7.2.1
> curl.exe --version
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
> iwr https://deno.land/x/install/install.ps1 -useb | iex
Invoke-WebRequest: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
```

PS: I use Windows 11 22000.376.

**Comment by saschanaz** [comment]
The script itself runs well when I download it manually.

```
> ./install
Deno was installed successfully to C:\Users\Kagami\.deno\bin\deno.exe
Run 'deno --help' to get started
```

**Comment by webdev3301** [comment]
It appears the reason for this error is the default tls protocol PowerShell uses to connect to the server before download.

The following command needs to be run before you run the PowerShell install script. It enables the tls protocols that will ultimately allow you to connect to the server and download setup files.

**First command**
`[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"`

**Second command**
`iwr https://deno.land/x/install/install.ps1 -useb | iex`

Good reads

[Powershell Invoke-WebRequest Fails with SSL/TLS Secure Channel](https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel)

[Default SecurityProtocol in .NET 4.5](https://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5)

**Comment by MarkTiedemann** [comment]
It seems like you are using the new cross-plattform `pwsh` v7.2. Using the default Windows `powershell` v5.1, it works fine.

**Comment by saschanaz** [comment]
> It seems like you are using the new cross-plattform `pwsh` v7.2. Using the default Windows `powershell` v5.1, it works fine.

No, it fails too, with a slightly different message but still about handshaking.

```
iwr : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:1
+ iwr https://deno.land/x/install/install.ps1 -useb | iex
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by saschanaz** [comment]
> The following command needs to be run before you run the PowerShell install script. It enables the tls protocols that will ultimately allow you to connect to the server and download setup files.

This doesn't work either, and your second SO post says recent versions of .NET shouldn't need it. 🤔

**Comment by MarkTiedemann** [comment]
> No, it fails too, with a slightly different message but still about handshaking.

What's your `$PSVersionTable`?

**Comment by webdev3301** [comment]
It initially didn't work for on Windows 11 Pro for Workstations. After running that command it did. Wonder why it's not working for you.

**Comment by saschanaz** [comment]
```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by saschanaz** [comment]
> It initially didn't work for on Windows 11 Pro for Workstations. After running that command it did. Wonder why it's not working for you.

Does your machine still requires you to set `SecurityProtocol` or was it one-time? If it was one-time then it should be something else on your machine, since that setting is not system persistent.

**Comment by lts20050703** [comment]
> It appears the reason for this error is the default tls protocol PowerShell uses to connect to the server before download.
> 
> The following command needs to be run before you run the PowerShell install script. It enables the tls protocols that will ultimately allow you to connect to the server and download setup files.
> 
> **First command** `[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"`
> 
> **Second command** `iwr https://deno.land/x/install/install.ps1 -useb | iex`
> 
> Good reads
> 
> [Powershell Invoke-WebRequest Fails with SSL/TLS Secure Channel](https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel)
> 
> [Default SecurityProtocol in .NET 4.5](https://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5)

![image](https://user-images.githubusercontent.com/87189679/148078904-67c6bfef-6f55-4602-b68f-11ea4e85e959.png)

**Comment by pf1gura** [comment]
> It appears the reason for this error is the default tls protocol PowerShell uses to connect to the server before download.
> 
> The following command needs to be run before you run the PowerShell install script. It enables the tls protocols that will ultimately allow you to connect to the server and download setup files.
> 
> **First command** `[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"`
> 
> **Second command** `iwr https://deno.land/x/install/install.ps1 -useb | iex`
> 
> Good reads
> 
> [Powershell Invoke-WebRequest Fails with SSL/TLS Secure Channel](https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel)
> 
> [Default SecurityProtocol in .NET 4.5](https://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5)

This worked for me when run in powershell.exe instead of cross-platform pwsh.exe

**Comment by webdev3301** [comment]
Just reporting back. I had to upgrade deno again and once again I got the error.

Then in Powrshell Run As Administrator, I once again run:

`[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"`

Then...

`iwr https://deno.land/x/install/install.ps1 -useb | iex`

...and download worked again.

**Comment by saschanaz** [comment]
It works for me today, closing. 

```
PowerShell 7.2.2
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

Loading personal and system profiles took 692ms.
C:\Users\Kagami> iwr https://deno.land/install.ps1 -useb | iex
Deno was installed successfully to C:\Users\Kagami\.deno\bin\deno.exe
Run 'deno --help' to get started
C:\Users\Kagami> deno --version
deno 1.20.3 (release, x86_64-pc-windows-msvc)
v8 10.0.139.6
typescript 4.6.2
C:\Users\Kagami>
```
