### ISSUE TITLE
Use irm instead of iwr -useb

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno_install#213]
`irm` is the alias for [Invoke-RestMethod](
https://docs.microsoft.com/en-us/previous-versions/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-3.0), which is available since PowerShell 3.

So `iwr https://deno.land/install.ps1 -useb | iex` could be shortened to `irm https://deno.land/install.ps1 | iex`.

**Comment by lucacasonato** [comment]
@piscisaureus @dsherret Thoughts?

**Comment by MarkTiedemann** [comment]
https://scoop.sh/ does this, too.

**Comment by dsherret** [comment]
Seems better. Powershell 3 was released 10 years ago.
