### ISSUE TITLE
 schannel: next InitializeSecurityContext failed: Unknown error  while installing deno on windows

### ISSUE THREAD

**Issue by imtheknown** [denoland/deno_install#223]
![deno](https://user-images.githubusercontent.com/18484079/182525140-c38210a9-7c04-4239-9f57-10541a109a8b.png)

**Comment by imtheknown** [comment]
Installed deno it by adding --ssl-no-revoke parameter on the curl command on installation script (install.ps1)

**Comment by kt3k** [comment]
cc @MarkTiedemann @dsherret

**Comment by MarkTiedemann** [comment]
Well, I don't think we should add `--ssl-no-revoke`. Just because the revocation server was offline in this case, we don't want to disable certificate revocation checks for all installs. 

> --ssl-no-revoke
> (Schannel) This option tells curl to disable certificate revocation checks. **WARNING: this option loosens the SSL security**, and by using this flag you ask for exactly that.

_https://curl.se/docs/manpage.html_

**Comment by kt3k** [comment]
ah, this was a temporary outage of revocation server.

@imtheknown Can you check that the install script works now?

**Comment by imtheknown** [comment]
@kt3k  @MarkTiedemann  Yes it does! Thanks for the help.

**Comment by APerricone** [comment]
I just faced this issue, to install deno I downloaded manually the zip, putted on the right directory and renamed.
I think it is not closed.
![image](https://user-images.githubusercontent.com/22457168/215942539-dc9ba1b3-fbca-4f26-b7f3-f97acbbca3dd.png)
Sorry for Italian message:

**Comment by swervx** [comment]
Hello, I have exactly the same problems
![Capture](https://user-images.githubusercontent.com/101983666/236650393-0d3dc0d3-9ac4-4aa0-a959-b6aa8a05b97f.PNG)
