### ISSUE TITLE
Feature Request: Add Deno as WinGet package

### ISSUE THREAD

**Issue by aidantomcy** [denoland/deno_install#227]
The idea for this feature is simple: i.e., to make Deno available to install via WinGet for Windows.  
Since Windows users can install Deno with Chocolatey or Scoop, it would be a good idea to be able to install Deno via WinGet, as it is installed by default on Windows.

Here is the link to the WinGet documentation, on how to add a package (if needed): [Submit packages to Windows Package Manager](https://docs.microsoft.com/en-us/windows/package-manager/package/)

**Comment by MarkTiedemann** [comment]
Duplicate of: https://github.com/denoland/deno/issues/5640

**Comment by aidantomcy** [comment]
Sorry!
