### ISSUE TITLE
Deno install should add to your bash/zsh config on first run if DENO_PATH is missing

### ISSUE THREAD

**Issue by itsdouges** [denoland/deno_install#231]
Hello! To get Deno install working I had to manually add it to my zsh config. It would be great if this was done automatically.

**Comment by kt3k** [comment]
This was tried multiple times before (#52 #157 #177 #178), but it's difficult and complex to detect the users' environment correctly. We rather prefer to keep the install script simple.

**Comment by itsdouges** [comment]
Ah ok no worries, that's fair enough. Just one extra piece of friction/step to get new users onto Deno though.
