### ISSUE TITLE
Add ability of install.sh to add the deno bin path to shell profile automatically.

### ISSUE THREAD

**Issue by h76oeI6pMxU9g4p8aCpc6Q** [denoland/deno_install#268]
This can automatically done with PowerShell (Windows):
https://github.com/denoland/deno_install/blob/master/install.ps1#L45

But need to manually done with Shell (Unix-like):
https://github.com/denoland/deno_install/blob/master/install.sh#L53

Like install.ps1, need to check whether deno bin path already exists in shell profile (Environment Variable in Windows) or not, only add path when not existed.

Finally, inform user to restart terminal or execute "source" shell profile commands to make "deno" command available immediately.

**Comment by kt3k** [comment]
We discussed this in the past several times, but we think this isn't worth it regarding the variety of environments in unix-like ecosystem.

ref #52 #157 #177 #178 #231
