### ISSUE TITLE
Improving the Windows installation process

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno_install#3]
Since both `curl` and `python` aren't pre-installed on Windows, `curl -sSf https://raw.githubusercontent.com/denoland/deno_install/master/install.py | python` is not a very convenient way to install `deno`.

Creating a proper `.msi` or `.exe` installer is probably too much work at the moment. However, adding `deno` to a Windows package manager is fairly easy.

As far as I know, there are two major package managers for Windows: [Chocolatey](https://github.com/chocolatey/choco) and [Scoop](https://github.com/lukesampson/scoop).

Since `scoop` is more actively maintained than `choco`, arguably easier to use, and focused on developer tools, I decided to make a PR for adding `deno` to `scoop`. Since it has already been merged, `deno` can be installed with `scoop install deno` on Windows.

I think in future, there should be multiple options for users to install `deno` on Windows:

- [ ] Download `deno.exe` file
- [X] Download `deno.zip` file
- [ ] Download `deno-setup.exe` file
- [x] Install from `powershell.exe`: `iex (iwr https://raw.githubusercontent.com/denoland/deno_install/master/install.ps1)` (see: [denoland/deno_install/#4](https://github.com/denoland/deno_install/pull/4))
- [x] Install from `pwsh.exe`: `iex (iwr https://raw.githubusercontent.com/denoland/deno_install/master/install.ps1)`
- [X] Install via Scoop: `scoop install deno` (see: [lukesampson/scoop/#2570](https://github.com/lukesampson/scoop/pull/2570))
- [ ] Install via Chocolatey: `choco install deno`
- [ ] Install via npm: `npm install deno`

**Comment by gocs** [comment]
Can we have `deno.land/deno.ts`?

**Comment by MarkTiedemann** [comment]
I think this issue can be closed for now. The Windows PowerShell installer is on par with the python installer. And in regards to package managers, I think Windows is ahead of MacOS with `scoop install deno` already working compared to `brew install deno` which is yet to be implemented.

**Comment by MarkTiedemann** [comment]
@ry I think `scoop` is the modern package manager for Windows. Might be that I live in a bubble, but I don't know anyone who's still using `choco`... It's basically Homebrew for Windows - not least because it is inspired by Homebrew. :)

I think a reference would be great. Even though I wrote the inital version of the PowerShell installer, I'm already using `scoop` to manage my `deno` installation.

**Comment by gluons** [comment]
Will Chocolatey installation come in the future? I usually use Chocolatey.

**Comment by zekth** [comment]
> Will Chocolatey installation come in the future?
> I usually use Chocolatey on my laptop.

At the moment only `scoop` is available. If someone want to work on this it's totally welcome but it's not in the scope of the development.
