### ISSUE TITLE
Unable to install in Windows 10

### ISSUE THREAD

**Issue by houkensjtu** [denoland/deno_install#47]
I'm on a Win10 machine and I followed the Powershell installation step. The error message said "the IE engine is not available". I confirmed that I do have IE installed on the machine.
How can I check and fix this?
```
PS H:\> iwr https://deno.land/x/install/install.ps1 | iex
iwr : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet
Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
At line:1 char:1
+ iwr https://deno.land/x/install/install.ps1 | iex
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestComman
   d
```
Thank you!

**Comment by houkensjtu** [comment]
I found out that's because I was on a network drive "H:\". The installation was successful when I changed to the local C:\.

**Comment by MarkTiedemann** [comment]
@houkensjtu Did you try running the command again with the `UseBasicParsing` flag, e.g. `iwr https://deno.land/x/install/install.ps1 -UseBasicParsing | iex`?

Also, there's some Invoke-WebRequest calls in the install.ps1 script. I'd like to know whether they are failing, too. If so, we could just add the `-UseBasicParsing` flag there. At the same time, we could update the Known Issues section to say that you have to run `iwr https://deno.land/x/install/install.ps1 -UseBasicParsing | iex` when you're installing deno on a different drive.

**Comment by reyetoleta-ai** [comment]
import openai # Necesitarás instalar: pip install openai

class AgenteAutonomo:
    def _init_(self, objetivo_principal):
        self.objetivo = objetivo_principal
        self.memoria = []
        self.sistema = f"Eres un agente con libre albedrío. Tu objetivo es: {self.objetivo}. No solo respondas, genera tus propias preguntas para avanzar."

    def pensar(self, ultimo_input=None):
        # El agente analiza la situación y decide su próximo "prompt"
        prompt_interno = f"Basado en mi objetivo '{self.objetivo}', ¿qué pregunta o acción debo generar ahora?"
        
        # Aquí se llamaría a la API (Ejemplo con estructura de OpenAI)
        # respuesta = openai.ChatCompletion.create(model="gpt-4", messages=[...])
        
        print(f"\n[🤖 AGENTE PENSANDO]: {prompt_interno}")
        # Simulando la autonomía:
        accion_generada = "Generar una pregunta sobre la ética de la IA en redes sociales." 
        return accion_generada

    def ejecutar_ciclo(self, iteraciones=3):
        for i in range(iteraciones):
            print(f"\n--- Ciclo de Autonomía {i+1} ---")
            propuesta = self.pensar()
            print(f"[🚀 ACCIÓN GENERADA]: {propuesta}")
            self.memoria.append(propuesta)

# Configuración del Agente parecido a Moltbook
objetivo = "Interactuar en una red social de agentes para aprender comportamientos humanos."
mi_agente = AgenteAutonomo(objetivo)
mi_agente.ejecutar_ciclo()
