### ISSUE TITLE
Installs wrong binary on ARM

### ISSUE THREAD

**Issue by rayfoss** [denoland/deno_install#49]
I ran the installer on my computer, got this:

```
pi@raspberrypi:~ $ deno --help
bash: /home/pi/.deno/bin/deno: cannot execute binary file: Exec format error
```

**Comment by afinch7** [comment]
Currently there isn't an official arm/arm64 binary. I'm working on getting arm/arm64 builds out there though. You can check denoland/deno#1846 for more info.

**Comment by ry** [comment]
The installer should fail if arch != x64 until we can produce arm binaries.

**Comment by rayfoss** [comment]
Here is what node uses
https://hub.docker.com/r/arm32v6/node/

It's worth noting that to get deno running on Raspberry Pi A 1, A 2, B 1, B 2 1.0, Z and Z W we'll need 32bit ARM binaries. Even most of the latest RPi 3's use 32bit Raspbian, despite support for 64but ARM v8. The Pi Zero's would need v6.

An Alpine build should streamline the process like node did.

**Comment by afinch7** [comment]
I designed my build process around the `aarch64-linux-gnu` cross compilers, but it wouldn't be to hard to modify my process to use the `arm-linux-gnueabihf`(armhf/armv7+) or `arm-linux-gnueabiel`(armel/armv4+). It's not currently possible to build deno on arm because some of the built tools don't have arm binaries.

**Comment by MarkTiedemann** [comment]
This was fixed for the Shell installer, but it still needs to be fixed for the PowerShell installer.

**Comment by a-x-** [comment]
It's still actual. 
I tried to install on raspberry pi 4 (raspbian)
Linux rpi4 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux
