### ISSUE TITLE
TLS 1.0 support

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno_install#56]
`https://deno.land/x/install/install.ps1` redirects to `https://raw.githubusercontent.com/denoland/deno_install/master/install.ps1`:

```
$ curl -I https://deno.land/x/install/install.ps1 | grep Location:
Location: https://raw.githubusercontent.com/denoland/deno_install/master/install.ps1
```

`deno.land` does **not** work with TLS 1.0.

```diff
$ curl --tls-max 1.2 https://deno.land/x/install/install.ps1
$ curl --tls-max 1.0 https://deno.land/x/install/install.ps1
-curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```

However, `raw.githubusercontent.com` works fine with TLS 1.0.

```
$ curl --tls-max 1.2 https://raw.githubusercontent.com/denoland/deno_install/master/install.ps1
$ curl --tls-max 1.0 https://raw.githubusercontent.com/denoland/deno_install/master/install.ps1
```

There have been a number of issues because PowerShell <v6 uses TLS 1.0 by default.

For example:

- https://github.com/denoland/deno_install/issues/51
- https://github.com/denoland/deno_install/issues/16
- https://github.com/denoland/deno/issues/1729

The default PowerShell version for Windows 8 is v4, for Windows 10 it is v5. So this impacts nearly all PowerShell users.

The following fixes are possible:

- (1) Changing the one-line install command to use TLS 1.2

```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iwr https://deno.land/x/install/install.ps1 | iex
```

- (2) Changing the one-line install command to point directly to GitHub

```powershell
iwr https://raw.githubusercontent.com/denoland/deno_install/master/install.ps1 | iex
```

- (3) Enabling TLS 1.0 for `deno.land`

cc @ry

**Comment by hayd** [comment]
I believe (3) is a CloudFront setting https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValues-security-policy

but (1) also seems fine.

**Comment by MarkTiedemann** [comment]
I'd like to avoid (1) purely because it makes the one-line install command very long...

**Comment by MarkTiedemann** [comment]
@ry Any chance we can enable TLS 1.0 for `deno.land` in CloudFront? This is still an issue.

```diff
$ curl --tlsv1.0 https://deno.land/x/install/install.ps1
-curl: (35) error:14004410:SSL routines:CONNECT_CR_SRVR_HELLO:sslv3 alert handshake failure
```

**Comment by ry** [comment]
I've turned on TLSv1.0 on cloudfront. Sorry that took so long.

**Comment by ry** [comment]
install.ps1 doesn't work still - I think github.com does not accept TLS 1.0 anymore?

**Comment by MarkTiedemann** [comment]
Thanks, @ry!

<details>
<summary>Yeah, you're right. The call to `deno.land` works now, but the call to `github.com` fails.</summary>
<pre>
PS C:\Users\mark> iwr https://deno.land/x/install/install.ps1 | iex
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At line:51 char:15
+ ... $Response = Invoke-WebRequest 'https://github.com/denoland/deno/relea ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
</pre>
</details>

Luckily, this calls is from within our installer script, so we can fix it by just adding `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12` to the top of the installer script.

Will make a PR tomorrow.

**Comment by MarkTiedemann** [comment]
@ry I don't think this is fixed yet, or maybe it's a weird Windows issue...

```
C:\>curl --version
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: [unreleased]
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL

C:\>curl --tlsv1.0 https://deno.land/x/install/install.ps1
curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.

C:\>powershell -c "$PSVersionTable"

Name                           Value
----                           -----
PSVersion                      5.1.17134.765
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.765
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

C:\>powershell -c "iwr https://deno.land/x/install/install.ps1"
iwr : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:1
+ iwr https://deno.land/x/install/install.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

```

**Comment by MarkTiedemann** [comment]
I'm starting to be in favor of prepending `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; ` to the install command until we've fixed this (if it is fixable at all).

**Comment by MarkTiedemann** [comment]
Just tested on my Windows machine. Can confirm this finally works now. :)
