### ISSUE TITLE
Add asdf installer

### ISSUE THREAD

**Issue by yordis** [denoland/deno_install#66]
`asdf` is a popular tool that helps a bit with the management of the languages (which `brew` doesn't give us a good solution for it, at least in MacOS)

Would be nice to have an `asdf` plugin for managing Deno

**Comment by M4rk9696** [comment]
There already seems to be one https://github.com/johnlayton/valdastreet

**Comment by kt3k** [comment]
Found this one as well. https://github.com/asdf-community/asdf-deno

**Comment by kt3k** [comment]
The above @johnlayton's plugin seems to be official one now. https://github.com/asdf-vm/asdf-plugins/pull/104
