### ISSUE TITLE
having folder "sh" in pwd will fail the install

### ISSUE THREAD

**Issue by dym-sh** [denoland/deno_install#67]
System: Ubuntu 18.04
Deno Version: v0.10.0 / 2019.06.25

----

tried to install deno from my home dir (it has a folder "sh" in it), so:

> (23) Failed writing body
> (pwd now: ~/sh)

does it have smth to do with /bin/sh ?
(re)installing from another folder works normally

**Comment by ry** [comment]
Im doubtful it’s related to the name of the directory. Can you provide the command you ran to install.

**Comment by dym-sh** [comment]
the one listed on the site: `curl -fsSL https://deno.land/x/install/install.sh | sh`

...oh, it's the pipe. anything named `sh` in pwd will be used before `/bin/sh`...

how about make it into  

```sh 
curl -fsSL https://deno.land/x/install/install.sh | $(which sh)
```

**Comment by MarkTiedemann** [comment]
Then we also have to make sure that `which` is installed, which I don't think is part of the POSIX standard (but `command` is). I think with this additional command you're opening up a whole other can of worms... I'd be fine with using `/bin/sh`, but I don't think this is a common issue. To me, this seems rather like a wont-fix.

In any case, if someone has this same exact issue, they can find this thread, and fix it then. :)

**Comment by dym-sh** [comment]
i saw how [Oh-My-Zsh](https://ohmyz.sh/) does this, and it works even with "sh" file in pwd:

```sh
sh -c "$(curl -fsSL https://deno.land/x/install/install.sh)"
```
