### ISSUE TITLE
install.sh should work in windows mingw shell

### ISSUE THREAD

**Issue by ry** [denoland/deno_install#68]

**Comment by BearD01001** [comment]
> Yes - somehow it’s not working in mingw denoland/deno_install#68
@BearD01001 try the powershell install command
(and delete the $HOME/.deno/bin/deno file)
>
>replied from @ry at [①deno/Lobby - Gitter](https://gitter.im/denolife/Lobby)

Leave it here in case of someone needed.

**Comment by ccheng** [comment]
So I got it to work with Git Bash, which I think is actually mingw shell, and I've tested it on Mac, Windows, and Ubuntu.
Is it ok to make a pull request?  Not sure how to go about this...
Thanks!

**Comment by ry** [comment]
@ccheng please do!
