### ISSUE TITLE
highlight.js considers closing single quote as part of URL

### ISSUE THREAD

**Issue by dym-sh** [denoland/deno_install#72]
see:
https://deno.land/x/install/install.ps1#L54
https://deno.land/x/install/install.ps1#L58
https://deno.land/x/install/install.ps1#L70

vs
https://github.com/denoland/deno_install/blob/master/install.ps1#L54-L70

this messes up highlighting for the rest of the file, making it harder to read than a plain text

**Comment by ry** [comment]
cc @j-f1
