### ISSUE TITLE
Unable to access https://deno.land from server with only IPv6

### ISSUE THREAD

**Issue by josephrocca** [denoland/deno_install#74]
I'm very much a noob when it comes to internet protocol stuff, and I was just trying to install Deno on a server that only has an IPv6 address:
```
$ curl -fsSL https://deno.land/x/install/install.sh | sh
curl: (7) Failed to connect to deno.land port 443: Connection timed out
```
Is this expected behavior?

**Comment by MarkTiedemann** [comment]
`curl -fsSL --ipv6 https://deno.land/x/install/install.sh` works on my machine. Might be a proxy or firewall issue, but I doubt it's related to `deno.land`.

**Comment by josephrocca** [comment]
Ah okay, thanks for that! I'll investigate the things you suggested.
