### ISSUE TITLE
Add asdf plugin to installation instruction list

### ISSUE THREAD

**Issue by imbsky** [denoland/deno_install#80]

**Comment by imbsky** [comment]
I wrote this plugin for asdf version manager.
https://github.com/asdf-community/asdf-deno

**Comment by TranquilMarmot** [comment]
Literally came here to open an issue to support `asdf`; I'll try your plugin out!

**Comment by imbsky** [comment]
Ah, this title was a little strange, maybe something like “Add to installation instruction list” was appropriate. If you guys don't mind, I want to add it to the list. Because it might help people who want to manage Deno versions.

**Comment by MarkTiedemann** [comment]
> I wrote this plugin for asdf version manager.

The script looks great. Thank you!

> something like “Add to installation instruction list” was appropriate

Yeah, I think it should be added in 3 places: the readme of this repo, the main page of the [deno.land](https://deno.land) website, and the install section of the manual.

**Comment by nayeemrmn** [comment]
I think the set of runtimes that asdf supports is for them to list. It's general purpose (and not as well-known as brew). It doesn't make sense to mention in in every project it supports... certainly not in three different places 😄

**Comment by imbsky** [comment]
Well, I don't have strong will to adding this. but for someone like me who wants to manage all, the existence of these tools can be a big factor in deciding whether to use them.

**Comment by imbsky** [comment]
and asdf is as popular as anyenv. It's not reasonable to list everything, but I think it's relatively meaningful to add some popular tools early on in the project to lower the psychological barrier for new famiries 😁

**Comment by imbsky** [comment]
I created a version manager for Deno with Native Reason (OCaml). If you're interested, check it out!
https://github.com/imbsky/dvm

**Comment by imbsky** [comment]
![image](https://user-images.githubusercontent.com/38746192/69303168-48bd1880-0c5f-11ea-856e-28bccedcf9e4.png)

**Comment by imbsky** [comment]
@TranquilMarmot I don't know if you are interested, but I can recommend this one!

> Shims are just tiny wrappers created by asdf that just forward execution to the real versioned executables installed by asdf. This way, asdf has a single shims directory added to your PATH and has no need of mangling the PATH for every installed version. When you run an asdf-managed command, like node, it will actually execute an asdf-shim, which will determine the node version to activate according to your .tool-versions file. A downside of this is that every single time you run node asdf will have to determine again which version to use. Even if you haven't changed your .tool-versions file to upgrade the node version to use. And this happens for every shim execution, which could lead to some users experiencing certain slowness while asdf is looking up versions, since it has to traverse directories looking up for a .tool-versions file and probably also legacy version files.

https://github.com/asdf-community/asdf-direnv

**Comment by TranquilMarmot** [comment]
Super interesting! Thanks for the explanation!

**Comment by imbsky** [comment]
dvm just creates a symbolic link to a specific version. So it works very fast. Of course, there is also a reason that it's fast because it runs as a native system binary.
