### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by imbsky** [denoland/deno_install#82]

**Comment by imbsky** [comment]
@ry I'm ready to submit the PR, what do you think?

**Comment by ry** [comment]
Thanks but I'd rather merge this repo into the main repo. I don't see a purpose of having it separate anymore.

**Comment by imbsky** [comment]
Yes, that's right. I have already written the config in https://github.com/imbsky/deno_install/commit/8838815794b19130d84b9a03e9969ccbef37f44e, so feel free to use them if you need.

**Comment by imbsky** [comment]
CI is faster because the installation and execution of ShellCheck, shfmt, and PSScriptAnalyzer are completely separate from the test scripts and run in parallel.
