### ISSUE TITLE
message keep appear to me

### ISSUE THREAD

**Issue by Adamkaram** [denoland/deno_install#96]
![Untitled](https://user-images.githubusercontent.com/52092726/76938506-462ab100-6929-11ea-8fbc-8ea9ab184fbf.png)

**Comment by kevinkassimo** [comment]
I am not quite sure about the problem why raw ANSI color code chars appear on PowerShell.

However, why are you trying to enter Deno commands under Deno REPL? That is not the way to use a REPL.

As to `for await (...)` error, `for-await-loop` is not yet a JS standard and is available only through TypeScript atm (Deno REPL only supports JS for now). Also `for-await-loop` is also not going to work top-level unless you are putting it into a module

**Comment by Adamkaram** [comment]
However, why are you trying to enter Deno commands under Deno REPL? That is not the way to use a REPL.
need more info about that to know what should i do in this case?

Deno REPL only supports JS for now 
for how long ?


Also for-await-loop is also not going to work top-level unless you are putting it into a module
how i can do this?

**Comment by ry** [comment]
This doesn't seem to be an issue for deno_install.  

Maybe best to bring this issue up in the chat room for help https://discord.gg/TGMHGv6
