### ISSUE TITLE
REPL cannot use import statement outside a module

### ISSUE THREAD

**Issue by danbulant** [denoland/deno_install#97]
I need to run commands in deno *without* saving them in file, so I use piping. Even though it has few weird things (such as returning undefined at the end), it works well. The only thing is when I try to import module, it doesn't work. Is there a way to fix that?

**Comment by bartlomieju** [comment]
Have you tried using `deno eval`?

**Comment by danbulant** [comment]
Oh didn't know about that. Will try. 

Also the code is provided just as arguments? Is there a length limit?

**Comment by danbulant** [comment]
Oh it worked, thanks!
